"""
Manual smoke-test helper.

Usage:
    python scripts/drop_test_task.py            # Drop a task and watch the vault
    python scripts/drop_test_task.py --watch    # Only watch (no task drop)

Steps it performs:
  1. Writes a test task to /mnt/c/MY_EMPLOYEE/Needs_Action/
  2. Prints the full vault state every 3 seconds so you can see the file
     move through: Needs_Action → In_Progress → Plans / Done / Logs
  3. Stops when the task lands in Done/ or you press Ctrl-C
"""

import sys
import time
import argparse
from pathlib import Path
from datetime import datetime

# Run from Hackathon-0/ directory
sys.path.insert(0, str(Path(__file__).parent.parent))

from src.vault.manager import VaultManager

VAULT_PATH = Path("/mnt/c/MY_EMPLOYEE")
WATCH_INTERVAL = 3          # seconds between state snapshots
TIMEOUT_SECONDS = 300       # give up after 5 minutes


# --------------------------------------------------------------------------- #
# Helpers
# --------------------------------------------------------------------------- #

def vault_state(vm: VaultManager) -> dict:
    state = {}
    for key in ("needs_action", "in_progress", "plan", "done", "logs", "pending_approval"):
        try:
            files = vm.list_files_in_folder(key)
            state[key] = [f.name for f in files]
        except Exception:
            state[key] = []
    return state


def print_state(state: dict, header: str = ""):
    width = 60
    print("\n" + "─" * width)
    if header:
        print(f"  {header}")
    print("─" * width)
    labels = {
        "needs_action":     "📥 Needs_Action",
        "in_progress":      "⚙️  In_Progress ",
        "plan":             "📋 Plans        ",
        "pending_approval": "🔔 Pending      ",
        "done":             "✅ Done         ",
        "logs":             "📝 Logs         ",
    }
    for key, label in labels.items():
        files = state.get(key, [])
        count = f"({len(files)})"
        names = ", ".join(files[:3]) + (" …" if len(files) > 3 else "")
        print(f"  {label} {count:>4}  {names}")
    print("─" * width)


# --------------------------------------------------------------------------- #
# Main
# --------------------------------------------------------------------------- #

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--watch", action="store_true",
                        help="Only watch the vault without dropping a task")
    args = parser.parse_args()

    vm = VaultManager(vault_path=VAULT_PATH)

    # ── Drop task ─────────────────────────────────────────────────────────── #
    task_name = None
    if not args.watch:
        ts = datetime.now().strftime("%Y%m%d_%H%M%S")
        task_name = f"smoke_test_{ts}.md"
        task_path = VAULT_PATH / "Needs_Action" / task_name

        content = f"""# Smoke Test Task

**Created:** {datetime.now().isoformat()}

## Description
This is an automated smoke-test task generated by `scripts/drop_test_task.py`.

## Action Required
1. Acknowledge this task.
2. Write a one-sentence summary to `Plans/smoke_test_{ts}.md`.
3. Move yourself to Done and output `<promise>TASK_COMPLETE</promise>`.

## Context
- Vault: {VAULT_PATH}
- Test run: {ts}
"""
        vm.write_file(task_path, content)
        print(f"\n✅  Dropped task → Needs_Action/{task_name}")
        print("   Now start the orchestrator in another terminal:\n")
        print(f"     cd /home/syedhuzaifa/AI-EMPLOYEE/Hackathon-0")
        print(f"     python main.py --mode orchestrator\n")

    # ── Watch loop ────────────────────────────────────────────────────────── #
    print("👀  Watching vault (Ctrl-C to stop)…")
    deadline = time.time() + TIMEOUT_SECONDS
    prev_state = None

    while time.time() < deadline:
        current = vault_state(vm)

        if current != prev_state:
            ts_label = datetime.now().strftime("%H:%M:%S")
            print_state(current, header=f"State at {ts_label}")
            prev_state = current

            # Success check: task landed in Done
            if task_name and task_name in current.get("done", []):
                print(f"\n🎉  Task '{task_name}' is in Done/  — flow complete!\n")
                return

        time.sleep(WATCH_INTERVAL)

    print("\n⏱  Timeout reached. Check the vault manually.\n")


if __name__ == "__main__":
    main()
